version: "3.9"
services:
  web:
    container_name: therapysense_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:8443"
    env_file: ./server/.env
    environment:
      PRODUCTION: production
      LOG_PATH: /var/logs/therapist/main.log
      ERROR_PATH: /var/logs/therapist/error.log
    volumes:
      - /etc/ssl/certs/:/etc/ssl/certs
      - /etc/ssl/private/:/etc/ssl/private
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    container_name: therapysense_mongo
    hostname: mongo
    env_file: .mongoenv
    image: mongo
    volumes:
      - data-volume:/data/db
      - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  logs:
  web-root:
    driver: local
